name: PR Validation

on:
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/PbfLite.slnx
      
    - name: Build solution
      run: dotnet build src/PbfLite.slnx --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test src/PbfLite.slnx --no-build --configuration Release --verbosity normal
