name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore src/PbfLite.slnx
      
    - name: Build solution
      run: dotnet build src/PbfLite.slnx --no-restore --configuration Release
      
    - name: Run tests
      run: dotnet test src/PbfLite.slnx --no-build --configuration Release --verbosity normal
      
    - name: Pack NuGet package
      run: dotnet pack src/PbfLite/PbfLite.csproj --no-build --configuration Release --output ./nupkg
      
    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    - name: Upload NuGet package artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: ./nupkg/*.nupkg
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./nupkg/*.nupkg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
